apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiflow-backend
  template:
    metadata:
      labels:
        app: sentiflow-backend
    spec:
      containers:
      - name: backend
        image: "525127693154.dkr.ecr.us-east-1.amazonaws.com/sentiflow-backend:latest"
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            value: "sqlite:///sentiflow.db"
          - name: FLASK_ENV
            value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: sentiflow-backend
spec:
  selector:
    app: sentiflow-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
