global:
  ecr:
    repository: "525127693154.dkr.ecr.us-east-1.amazonaws.com"
    region: "us-east-1"

backend:
  image:
    name: "sentiflow-backend"
    tag: "latest"
  replicaCount: 1
  service:
    port: 5000

frontend:
  image:
    name: "sentiflow-frontend"
    tag: "latest"
  replicaCount: 1
  service:
    port: 3000

ingress:
  enabled: true
  host: "sentiflow.local"