replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "15-alpine" # גרסה קלה ומהירה

service:
  type: ClusterIP
  port: 5432

# משתני הסביבה של פוסטגרס (חייבים להתאים ל-Backend!)
env:
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "sentiflow"

# דרישות משאבים
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi