name: SentiFlow CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  AWS_REGION: us-east-1
  ECR_REPO_BACKEND: sentiflow-backend
  ECR_REPO_FRONTEND: sentiflow-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # אין צורך ב-Session Token כי יש לך מפתח קבוע (AKIA)
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Create ECR Repositories if missing
      run: |
        aws ecr describe-repositories --repository-names ${{ env.ECR_REPO_BACKEND }} || aws ecr create-repository --repository-name ${{ env.ECR_REPO_BACKEND }}
        aws ecr describe-repositories --repository-names ${{ env.ECR_REPO_FRONTEND }} || aws ecr create-repository --repository-name ${{ env.ECR_REPO_FRONTEND }}

    - name: Build & Push Backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd backend
        docker build -t $ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPO_BACKEND:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPO_BACKEND:latest
        docker push $ECR_REGISTRY/$ECR_REPO_BACKEND:latest

    - name: Build & Push Frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd frontend
        docker build -t $ECR_REGISTRY/$ECR_REPO_FRONTEND:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPO_FRONTEND:$IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPO_FRONTEND:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPO_FRONTEND:latest
        docker push $ECR_REGISTRY/$ECR_REPO_FRONTEND:latest